-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-22 18:57:17 EDT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE


-- Création de la table billet 
CREATE TABLE billet (
    id_billet                        NUMBER NOT NULL,
    prix                             FLOAT(40) NOT NULL,
    
);


ALTER TABLE billet ADD CONSTRAINT billet_pk PRIMARY KEY ( id_billet );


-- Insertion de données dans la table billet

INSERT INTO billet (id_billet, prix) VALUES (1323,10.50);
INSERT INTO billet (id_billet, prix) VALUES (2312,3.99);
INSERT INTO billet (id_billet, prix) VALUES (3578,2.50);
INSERT INTO billet (id_billet, prix) VALUES (434,22.99);
INSERT INTO billet (id_billet, prix) VALUES (575,7.99);


COMMIT;

SELECT *
FROM BILLET;



-- Création de la table evenement
CREATE TABLE evenement (
    id_evenement NUMBER NOT NULL,
    nom_evenement          VARCHAR2(255) NOT NULL,
    description  VARCHAR2(1000) NOT NULL
);

ALTER TABLE evenement ADD CONSTRAINT evenement_pk PRIMARY KEY ( id_evenement );

-- Insertion de données dans la table evenement

INSERT INTO evenement (id_evenement, nom_evenement, description) VALUES (243, "Festival Oriental","Festival qui célèbre l'histoire de l'Asie");
INSERT INTO evenement (id_evenement, nom_evenement, description) VALUES (3213, "Festival international de Jazz","Festival qui célèbre l'histoire du Jazz au Québec");
INSERT INTO evenement (id_evenement, nom_evenement, description) VALUES (123, "Expo de Jeux Vidéos","Venez voir cette exposition des meilleurs jeux vidéos de l'année.");
INSERT INTO evenement (id_evenement, nom_evenement, description) VALUES (452, "Fan Expo","Venez participer à cette exposition si vous êtes fans de Marvel, DC et d'animées");



COMMIT;

SELECT *
FROM EVENEMENT;


-- Création de la table organisateur

CREATE TABLE organisateur (
    id_organisateur NUMBER NOT NULL,
    nom_organisateur  VARCHAR2(255) NOT NULL
);

ALTER TABLE organisateur ADD CONSTRAINT organisateur_pk PRIMARY KEY ( id_organisateur );

-- Insertion de données dans la table organisateur

INSERT INTO organisateur (id_organisateur, nom) VALUES (23,"Micheal Jordan");
INSERT INTO organisateur (id_organisateur, nom) VALUES (2312,"Asuna Yuuki");
INSERT INTO organisateur (id_organisateur, nom) VALUES (438, "Ezio Auditore");
INSERT INTO organisateur (id_organisateur, nom) VALUES (483, "Harry Potter");
INSERT INTO organisateur (id_organisateur, nom) VALUES (1, "Micheal Scofield");


COMMIT;

SELECT *
FROM ORGANISATEUR;

-- Création de la table représentation

CREATE TABLE representation (
    id_representation      NUMBER NOT NULL,
    "Date"                 DATE NOT NULL,
    heure                  DATE NOT NULL,
    lieu                   VARCHAR2(255)NOT NULL,
    
);

ALTER TABLE representation ADD CONSTRAINT representation_pk PRIMARY KEY ( id_representation );

-- Insertion de données dans la table representation

INSERT INTO representation (id_representation, "Date", heure, lieu) VALUES (231,2024-08-23 , 10:30:00 ,"Centre Bell");
INSERT INTO representation (id_representation, "Date", heure, lieu) VALUES (34,2024-07-15 , 16:45:00 ,"Place Bell");
INSERT INTO representation (id_representation, "Date", heure, lieu) VALUES (778,2024-07,3, 12:30:00 , "Place des Arts");
INSERT INTO representation (id_representation, "Date", heure, lieu) VALUES (53,2024-08,5, 12:00:00 , "Place des Arts");
INSERT INTO representation (id_representation, "Date", heure, lieu) VALUES (12,2024-07-16, 14:30:00,"Centre Bell");


COMMIT;

SELECT *
FROM REPRESENTATION;

-- Création de la table utilisateur

CREATE TABLE utilisateur (
    id_utilisateur INTEGER NOT NULL,
    nom_utilisateur VARCHAR2(255) NOT NULL,
    email          VARCHAR2(255) NOT NULL,
);

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( id_utilisateur );

-- Insertion de données dans la table utilisateur

INSERT INTO utilisateur (id_utilisateur, nom_utilisateur, email) VALUES (22, "lebronfan_123","lebronfan_123@gmail.com");
INSERT INTO utilisateur (id_utilisateur, nom_utilisateur, email) VALUES (23,"Justin Dugazon","justindugazon1322@gmail.com");
INSERT INTO utilisateur (id_utilisateur, nom_utilisateur, email) VALUES (45,"Mcfly et Carlito","mcflycarlito@gmail.com");
INSERT INTO utilisateur (id_utilisateur, nom_utilisateur, email) VALUES (123,"fortnitePlayer_dr23123","fortnitePlayer.dr23123@hotmail.com");



COMMIT;

SELECT *
FROM UTILISATEUR;


ALTER TABLE billet
    ADD CONSTRAINT billet_representation_fk FOREIGN KEY ( representation_id_representation )
        REFERENCES representation ( id_representation );

ALTER TABLE organisateur
    ADD CONSTRAINT organisateur_evenement_fk FOREIGN KEY ( evenement_id_evenement )
        REFERENCES evenement ( id_evenement );


ALTER TABLE utilisateur
    ADD CONSTRAINT utilisateur_evenement_fk FOREIGN KEY ( evenement_id_evenement )
        REFERENCES evenement ( id_evenement );

ALTER TABLE representation
    ADD CONSTRAINT representation_evenement_fk FOREIGN KEY ( evenement_id_evenement )
        REFERENCES evenement ( id_evenement );






-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
