-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-22 18:57:17 EDT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE billet (
    id_billet                        INTEGER NOT NULL,
    prix                             FLOAT(40) NOT NULL,
    repr�sentation_id_repr�sentation INTEGER NOT NULL
);

ALTER TABLE billet ADD CONSTRAINT billet_pk PRIMARY KEY ( id_billet );

CREATE TABLE �v�nement (
    id_�v�nement INTEGER NOT NULL,
    nom          VARCHAR2(255) NOT NULL,
    description  VARCHAR2(1000) NOT NULL
);

ALTER TABLE �v�nement ADD CONSTRAINT �v�nement_pk PRIMARY KEY ( id_�v�nement );

CREATE TABLE "Evenement_-_Organisateur" (
    �v�nement_id_�v�nement       INTEGER NOT NULL,
    organisateur_id_organisateur INTEGER NOT NULL
);

ALTER TABLE "Evenement_-_Organisateur" ADD CONSTRAINT "Evenement_-_Organisateur_PK" PRIMARY KEY ( �v�nement_id_�v�nement,
                                                                                                  organisateur_id_organisateur );

CREATE TABLE "Evenement_-_Utilisateur" (
    �v�nement_id_�v�nement     INTEGER NOT NULL,
    utilisateur_id_utilisateur INTEGER NOT NULL
);

ALTER TABLE "Evenement_-_Utilisateur" ADD CONSTRAINT "Evenement_-_Utilisateur_PK" PRIMARY KEY ( �v�nement_id_�v�nement,
                                                                                                utilisateur_id_utilisateur );

CREATE TABLE organisateur (
    id_organisateur INTEGER NOT NULL,
    nom             VARCHAR2(255) NOT NULL
);

ALTER TABLE organisateur ADD CONSTRAINT organisateur_pk PRIMARY KEY ( id_organisateur );

CREATE TABLE repr�sentation (
    id_repr�sentation      INTEGER NOT NULL,
    "Date"                 DATE NOT NULL,
    heure                  DATE NOT NULL,
    lieu                   VARCHAR2(255)
     NOT NULL,
    �v�nement_id_�v�nement INTEGER NOT NULL
);

ALTER TABLE repr�sentation ADD CONSTRAINT repr�sentation_pk PRIMARY KEY ( id_repr�sentation );

CREATE TABLE utilisateur (
    id_utilisateur INTEGER NOT NULL,
    nomutilisateur VARCHAR2(255) NOT NULL,
    email          VARCHAR2(255) NOT NULL,
    motdepasse     VARCHAR2(255) NOT NULL
);

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( id_utilisateur );

ALTER TABLE billet
    ADD CONSTRAINT billet_repr�sentation_fk FOREIGN KEY ( repr�sentation_id_repr�sentation )
        REFERENCES repr�sentation ( id_repr�sentation );

ALTER TABLE "Evenement_-_Organisateur"
    ADD CONSTRAINT "Evenement_-_Organisateur_�v�nement_FK" FOREIGN KEY ( �v�nement_id_�v�nement )
        REFERENCES �v�nement ( id_�v�nement );

ALTER TABLE "Evenement_-_Organisateur"
    ADD CONSTRAINT "Evenement_-_Organisateur_Organisateur_FK" FOREIGN KEY ( organisateur_id_organisateur )
        REFERENCES organisateur ( id_organisateur );

ALTER TABLE "Evenement_-_Utilisateur"
    ADD CONSTRAINT "Evenement_-_Utilisateur_�v�nement_FK" FOREIGN KEY ( �v�nement_id_�v�nement )
        REFERENCES �v�nement ( id_�v�nement );

ALTER TABLE "Evenement_-_Utilisateur"
    ADD CONSTRAINT "Evenement_-_Utilisateur_Utilisateur_FK" FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE repr�sentation
    ADD CONSTRAINT repr�sentation_�v�nement_fk FOREIGN KEY ( �v�nement_id_�v�nement )
        REFERENCES �v�nement ( id_�v�nement );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
